name       : python-pyside6
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-6.2.2-src/pyside-setup-opensource-src-6.2.2.tar.xz : 70a74c7c7c9e5af46cae5b1943bc39a1399c4332b342d2c48103a1cfe99891a8
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : programming.python
summary    : Shiboken generates bindings for C++ libraries using CPython source code
description: |
    PySide6 is the official Python module from the Qt for Python project, which provides access to the complete Qt6 framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt63DCore)
    - pkgconfig(Qt6Bluetooth)
    - pkgconfig(Qt6Charts)
    - pkgconfig(Qt6DataVisualization)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6NetworkAuth)
    - pkgconfig(Qt6RemoteObjects)
    - pkgconfig(Qt6Scxml)
    - pkgconfig(Qt6Sensors)
    - pkgconfig(Qt6SerialPort)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebSockets)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(libxslt)
    - pkgconfig(shiboken6)
    - pkgconfig(xcb)
    - qt6-positioning-devel
    - designer6
    - numpy
    - python-six
setup      : |
    %patch -p1 < $pkgfiles/designer-plugin-install-path.patch
    mkdir qinclude
    cp -R /usr/include/qt* qinclude
    cd sources/pyside6
    sed -i 's|--include-paths=|--include-paths=%workdir%/qinclude:|' cmake/Macros/PySideModules.cmake
    %cmake_ninja \
        -DBUILD_TESTS=OFF \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DNUMPY_INCLUDE_DIR=$(python3 -c "import site; print(site.getsitepackages()[0])")/numpy/core/include
build      : |
    cd sources/pyside6
    %ninja_build
install    : |
    pushd sources/pyside6
    %ninja_install
    popd

    export PATH=/usr/lib64/qt6/bin:$PATH
    python3 setup.py egg_info --build-type=pyside6
    cp -r PySide6.egg-info $installdir/$(python3 -c "import site; print(site.getsitepackages()[0])")
    %python3_compile
